# Generated by Django 5.2.11 on 2026-03-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(help_text='Idempotency key — duplicate Kafka messages are safely ignored.', unique=True)),
                ('short_code', models.CharField(db_index=True, help_text='Denormalized short code (avoids FK join on hot read path).', max_length=16)),
                ('clicked_at', models.DateTimeField(db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Anonymized or raw client IP.', null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary event metadata (country, device, etc.).')),
            ],
            options={
                'db_table': 'click_events',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['short_code', '-clicked_at'], name='idx_click_code_time')],
                'constraints': [models.UniqueConstraint(fields=('event_id',), name='uq_click_event_id')],
            },
        ),
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField(help_text='The original long URL that was shortened.')),
                ('short_code', models.CharField(db_index=True, help_text='The unique short identifier (Base62, 7-16 chars).', max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiry. NULL means never expires.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag. Inactive URLs return 410 Gone.')),
            ],
            options={
                'db_table': 'urls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='idx_urls_expires_at')],
                'constraints': [models.UniqueConstraint(fields=('short_code',), name='uq_urls_short_code')],
            },
        ),
    ]
